/*
 * SimKube API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::*;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExportRequest {
    #[serde(rename = "start_ts")]
    pub start_ts: i64,
    #[serde(rename = "end_ts")]
    pub end_ts: i64,
    #[serde(rename = "filters")]
    pub filters: Box<ExportFilters>,
}

impl ExportRequest {
    pub fn new(start_ts: i64, end_ts: i64, filters: ExportFilters) -> ExportRequest {
        ExportRequest { start_ts, end_ts, filters: Box::new(filters) }
    }
}
