// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f k8s/raw/simkube.io_simulationroots.yaml
// kopium version: 0.15.0

use kube::CustomResource;
use serde::{Serialize, Deserialize};

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(group = "simkube.io", version = "v1", kind = "SimulationRoot", plural = "simulationroots")]
#[kube(namespaced)]
#[kube(schema = "disabled")]
pub struct SimulationRootSpec {
}

