---
apiVersion: kwok.x-k8s.io/v1alpha1
kind: Stage
metadata:
  name: pod-complete
spec:
  resourceRef:
    apiGroup: v1
    kind: Pod
  selector:
    matchExpressions:
      - key: .metadata.labels."simkube.kwok.io/stage-complete"
        operator: Exists
      - key: .metadata.deletionTimestamp
        operator: DoesNotExist
      - key: .status.phase
        operator: In
        values:
          - Running
  delay:
    durationFrom:
      expressionFrom: .metadata.annotations."simkube.kwok.io/stage-complete-time"
  next:
    patches:
      - subresource: status
        root: status
        template: |
          {{ $now := Now }}
          {{ $root := . }}
          containerStatuses:
          {{ range $index, $item := .spec.containers }}
          {{ $origin := index $root.status.containerStatuses $index }}
          - image: {{ $item.image | Quote }}
            name: {{ $item.name | Quote }}
            ready: false
            restartCount: 0
            started: false
            state:
              terminated:
                exitCode: 0
                finishedAt: {{ $now | Quote }}
                reason: Completed
                startedAt: {{ $now | Quote }}
          {{ end }}
          phase: Succeeded
