[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CDLA-Permissive-2.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "NCSA",
    "Unlicense",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.8
unused-allowed-license = "allow"
# ignore private workspace members
private = { ignore = true }
