---
preStartHooks:
  - cmd: kubectl
    args:
      - apply
      - -f
      - /config/metrics/autoscaler-podmonitor-hd.yml
preRunHooks:
  - cmd: kubectl
    args:
      - wait
      - --for=condition=Ready
      - -n
      - kube-system
      - -l
      - app.kubernetes.io/component=autoscaler
      - pod
      - --timeout
      - 1m
postRunHooks:
  - cmd: kubectl
    args:
      - delete
      - node
      - -l
      - type=virtual
  - cmd: kubectl
    args:
      - delete
      - pod
      - -n
      - kube-system
      - -l
      - app.kubernetes.io/component=autoscaler
