FROM debian:bookworm-slim AS builder

ARG K8S_VERSION=v1.34.3

RUN apt-get update && apt-get install -y \
    curl \
    dumb-init

RUN curl -L "https://dl.k8s.io/release/${K8S_VERSION}/bin/linux/amd64/kubectl" -o /usr/bin/kubectl
RUN chmod +x /usr/bin/kubectl

FROM gcr.io/distroless/cc-debian12:nonroot

COPY sk-driver /sk-driver
COPY --from=builder /usr/bin/dumb-init /usr/bin/dumb-init
COPY --from=builder /usr/bin/kubectl /usr/bin/kubectl

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
