/*
 * SimKube API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::*;

#[derive(Clone, Debug, Default, Deserialize, PartialEq, Serialize)]
pub struct ExportRequest {
    #[serde(rename = "start_ts")]
    pub start_ts: i64,
    #[serde(rename = "end_ts")]
    pub end_ts: i64,
    #[serde(rename = "export_path")]
    pub export_path: String,
    #[serde(rename = "filters")]
    pub filters: Box<ExportFilters>,
    #[serde(rename = "transform", skip_serializing_if = "Option::is_none")]
    pub transform: Option<String>,
}

impl ExportRequest {
    pub fn new(start_ts: i64, end_ts: i64, export_path: String, filters: ExportFilters) -> ExportRequest {
        ExportRequest {
            start_ts,
            end_ts,
            export_path,
            filters: Box::new(filters),
            transform: None,
        }
    }
}
