/*
 * SimKube API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 *
 * Generated by: https://openapi-generator.tech
 */

use super::*;

#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ExportFilters {
    #[serde(rename = "excluded_namespaces")]
    pub excluded_namespaces: Vec<String>,
    #[serde(rename = "excluded_labels")]
    pub excluded_labels: Vec<metav1::LabelSelector>,
}

impl ExportFilters {
    pub fn new(excluded_namespaces: Vec<String>, excluded_labels: Vec<metav1::LabelSelector>) -> ExportFilters {
        ExportFilters { excluded_namespaces, excluded_labels }
    }
}
