---
trackedObjects:
  apps/v1.Deployment:
    podSpecTemplatePaths:
      - /spec/template
  apps/v1.StatefulSet:
    podSpecTemplatePaths:
      - /spec/template
  batch/v1.CronJob:
    podSpecTemplatePaths:
      - /spec/jobTemplate/spec/template
    trackLifecycle: true
