---
openapi: 3.1.0
info:
  title: SimKube API
  version: "1"
paths:
  /export:
    post:
      summary: Export simulation data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              title: export_request
              required:
                - start_ts
                - end_ts
                - export_path
                - filters
              properties:
                start_ts:
                  type: integer
                  format: int64
                end_ts:
                  type: integer
                  format: int64
                export_path:
                  type: string
                  format: uri
                # TODO - eventually want positive filters too
                filters:
                  type: object
                  title: export_filters
                  required:
                    - excluded_namespaces
                    - excluded_labels
                  properties:
                    excluded_namespaces:
                      type: array
                      items:
                        type: string
                    excluded_labels:
                      type: array
                      items:
                        $ref: "#/components/schemas/LabelSelector"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                title: export_response
                properties:
                  trace_data:
                    type: string
                    format: byte
        "404":
          description: Storage location not found
        "500":
          description: Tracer error
        "502":
          description: External storage provider error
components:
  schemas:
    LabelSelector:
      description: "This is a copy of the upstream k8s LabelSelectorRequirement specification."
      properties:
        matchExpressions:
          type: array
          items:
            allOf:
              - $ref: "#/components/schemas/LabelSelectorRequirement"
        matchLabels:
          type: object
          additionalProperties:
            type: string
    LabelSelectorRequirement:
      description: "This is a copy of the upstream k8s LabelSelectorRequirement specification."
      required:
        - key
        - operator
      properties:
        key:
          type: string
        operator:
          type: string
          enum:
            - In
            - NotIn
            - Exists
            - DoesNotExist
        values:
          type: array
          items:
            type: string
