---
name: Setup Rust Builder
runs:
  using: composite
  steps:
    - name: Set up rust tools
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.88.0
        components: clippy
        cache-directories: |
          ./.build
          /tmp/cargo
    - name: Run sccache
      uses: mozilla-actions/sccache-action@v0.0.9
