---
name: Publish to Quay.io and Crates.io

on:  # yamllint disable-line rule:truthy
  release:
    types: [published]
env:
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: sccache
  IN_CI: "true"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Fetch tags
        run: git fetch --tags
      - name: Setup Builder
        uses: ./.github/actions/setup-builder
      - name: Install cargo workspaces
        run: cargo install cargo-workspaces@0.3.6 --locked
      - name: Build
        run: EXTRA_BUILD_ARTIFACTS= make build
      - name: Login to Quay.io
        run: >
          echo "${{ secrets.QUAY_IO_PASSWORD }}" |
          docker login quay.io -u "${{ secrets.QUAY_IO_USERNAME }}" --password-stdin
      - name: Build and push Docker image
        run: DOCKER_REGISTRY=quay.io/appliedcomputing make image
      - name: Logout from Quay.io
        run: docker logout quay.io
      - name: Login to crates.io
        run: echo "${{ secrets.CRATES_IO_PASSWORD }}" | cargo login
      - name: Publish to crates.io
        run: make publish
      - name: Logout from crates.io
        run: cargo logout
