---
name: code verification
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "main"
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: sccache
  IN_CI: "true"
  RUST_NIGHTLY_VERSION: 2026-01-01

permissions: {}

jobs:
  skctl:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Setup Builder
        uses: ./.github/actions/setup-builder
      - name: Build skctl
        run: make skctl
      - name: Check version
        run: .build/skctl --version

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Setup Builder
        uses: ./.github/actions/setup-builder
      - name: Build
        run: make build
      - name: Regenerate CRDs
        run: .build/skctl crd > k8s/raw/simkube.io_simulations.yml
      - name: Check CRDs are clean
        uses: CatChen/check-git-status-action@cc5a79733c441f67cd0cd076de116cd2eebcebfe  # v2.1.3
        with:
          fail-if-not-clean: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Setup Builder
        uses: ./.github/actions/setup-builder
      - name: Install rustfmt nightly
        run: |
          rustup toolchain install nightly-${RUST_NIGHTLY_VERSION}
          rustup component add rustfmt --toolchain nightly-${RUST_NIGHTLY_VERSION}
      - name: Install Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a  # v1.4.1
      - name: Run pre-commit
        uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo and build scripts
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          submodules: recursive
          persist-credentials: false
      - name: Setup Builder
        uses: ./.github/actions/setup-builder
      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly-${RUST_NIGHTLY_VERSION}
      - name: Install cargo-nextest
        uses: taiki-e/install-action@0fde6d128a3d980ceac30be8c8b8739abd963b81  # v2.70.0
        with:
          tool: cargo-nextest
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@0fde6d128a3d980ceac30be8c8b8739abd963b81  # v2.70.0
        with:
          tool: cargo-llvm-cov
      - name: Test
        run: make test cover
      - name: Upload coverage
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2  # v6.0.0
        with:
          files: codecov.lcov
          fail_ci_if_error: true
